"""Generate the enterprise architecture diagram (docs/architecture.png) with pure PIL.

Run:  python3 scripts/generate_diagram.py
Output: docs/architecture.png
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

OUT = Path(__file__).resolve().parent.parent / "docs" / "architecture.png"
W, H = 1280, 900

BG = (15, 23, 42)
PANEL = (30, 41, 59)
PANEL_LINE = (51, 65, 85)
TEXT = (226, 232, 240)
TEXT_DIM = (148, 163, 184)
ACCENT = (96, 165, 250)
ACCENT_2 = (52, 211, 153)
ACCENT_3 = (251, 191, 36)
DANGER = (248, 113, 113)

LAYOUT = [
    # (name, x, y, w, h, color)
    ("Client (curl / App / Web)", 40, 40, 360, 90, DANGER),
    ("FastAPI (ASGI)", 440, 40, 360, 90, ACCENT),
    ("Logging (JSON)", 840, 40, 400, 40, PANEL_LINE),
    ("Auth (Bearer)", 840, 92, 400, 40, PANEL_LINE),
    ("Routers v1", 840, 144, 400, 40, PANEL_LINE),
    ("Middleware (CORS/GZip)", 840, 196, 400, 40, PANEL_LINE),
    ("Ingestion Service", 90, 300, 320, 100, ACCENT_2),
    ("Retrieval Service", 480, 300, 320, 100, ACCENT_2),
    ("Agent / LLM Service", 870, 300, 320, 100, ACCENT_3),
    ("SQLite (docs + chunks + FTS5)", 90, 560, 1100, 130, ACCENT),
]


def _font(size: int):
    for name in ("Arial.ttf", "DejaVuSans.ttf", "Helvetica.ttc"):
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _rounded(draw: ImageDraw.ImageDraw, box, radius, fill, outline=None):
    draw.rounded_rectangle(box, radius=radius, fill=fill, outline=outline, width=2)


def _arrow(draw: ImageDraw.ImageDraw, x1, y1, x2, y2):
    draw.line([(x1, y1), (x2, y2)], fill=TEXT_DIM, width=2)
    # arrowhead
    dx, dy = x2 - x1, y2 - y1
    length = max(1, (dx * dx + dy * dy) ** 0.5)
    ux, uy = dx / length, dy / length
    size = 9
    p1 = (x2 - ux * size - uy * size, y2 - uy * size + ux * size)
    p2 = (x2 - ux * size + uy * size, y2 - uy * size - ux * size)
    draw.polygon([(x2, y2), p1, p2], fill=TEXT_DIM)


def main() -> None:
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    title = _font(30)
    sub = _font(20)
    node = _font(18)
    small = _font(15)

    d.text((40, 8), "Enterprise AI Agent Platform — Architecture", font=title, fill=TEXT)
    d.text((40, 50), "RAG + Agent + Multi-LLM · FastAPI · SQLite FTS5", font=sub, fill=TEXT_DIM)

    # Draw boxes with labels + sub-labels
    for name, x, y, w, h, color in LAYOUT:
        _rounded(d, (x, y, x + w, y + h), 12, PANEL, color)
        label = name.split(" (")[0]
        detail = name.split(" (")[1].rstrip(")") if " (" in name else ""
        tw = d.textlength(label, font=node)
        d.text((x + (w - tw) / 2, y + 12), label, font=node, fill=TEXT)
        if detail:
            dw = d.textlength(detail, font=small)
            d.text((x + (w - dw) / 2, y + 52), detail, font=small, fill=TEXT_DIM)

    # Arrows: Client -> FastAPI -> services -> DB
    _arrow(d, 400, 85, 440, 85)
    _arrow(d, 800, 85, 840, 85)
    _arrow(d, 250, 130, 250, 300)  # FastAPI -> ingestion
    _arrow(d, 620, 130, 620, 300)  # FastAPI -> retrieval
    _arrow(d, 1030, 130, 1030, 300)  # FastAPI -> agent
    _arrow(d, 250, 400, 250, 560)  # ingestion -> db
    _arrow(d, 620, 400, 620, 560)  # retrieval -> db
    _arrow(d, 1030, 400, 1030, 560)  # agent -> db

    # Legend
    lx, ly = 90, 730
    d.text((lx, ly), "圖例", font=node, fill=TEXT)
    for i, (label, color) in enumerate(
        [("外部客戶端", DANGER), ("服務層", ACCENT_2), ("Agent / LLM", ACCENT_3), ("資料層", ACCENT)]
    ):
        yy = ly + 34 + i * 34
        _rounded(d, (lx, yy, lx + 18, yy + 18), 4, PANEL, color)
        d.text((lx + 30, yy - 1), label, font=small, fill=TEXT_DIM)

    d.text((W - 300, H - 40), "generated by scripts/generate_diagram.py", font=small, fill=TEXT_DIM)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT, "PNG")
    print(f"written: {OUT}")


if __name__ == "__main__":
    main()